// Auto-generated by build.js — do not edit.
package com.imin.designsystem.tokens

import androidx.compose.ui.unit.dp

object Spacing {
    val spacing00px = 0.dp
    val spacing052px = 2.dp
    val spacing14px = 4.dp
    val spacing28px = 8.dp
    val spacing312px = 12.dp
    val spacing416px = 16.dp
    val spacing520px = 20.dp
    val spacing624px = 24.dp
    val spacing832px = 32.dp
    val spacing1040px = 40.dp
    val spacing1248px = 48.dp
    val spacing1664px = 64.dp
    val spacing2080px = 80.dp
    val spacing2496px = 96.dp
    val spacing32128px = 128.dp
    val spacing40160px = 160.dp
    val spacing48192px = 192.dp
    val spacing56224px = 224.dp
    val spacing64256px = 256.dp
    val spacing96384px = 384.dp
    val spacing80320px = 320.dp
    val spacing120480px = 480.dp
    val spacing160640px = 640.dp
    val spacing192768px = 768.dp
    val spacing2561024px = 1024.dp
    val spacing3201280px = 1280.dp
    val spacing3601440px = 1440.dp
    val spacing4001600px = 1600.dp
    val spacing4801920px = 1920.dp
    val spacing156px = 6.dp
    val spacing140560px = 560.dp
    val spacing180720px = 720.dp
    val spacingNone = 0.dp
    val spacingXxs = 2.dp
    val spacingXs = 4.dp
    val spacingMd = 8.dp
    val spacingLg = 12.dp
    val spacingXl = 16.dp
    val spacing2xl = 20.dp
    val spacing3xl = 24.dp
    val spacing4xl = 32.dp
    val spacing6xl = 48.dp
    val spacing7xl = 64.dp
    val spacing8xl = 80.dp
    val spacing9xl = 96.dp
    val spacing10xl = 128.dp
    val spacing11xl = 160.dp
    val spacingSm = 6.dp
    val spacing5xl = 40.dp
}

object Radius {
    val radiusNone = 0.dp
    val radiusXxs = 4.dp
    val radiusXs = 6.dp
    val radiusSm = 8.dp
    val radiusMd = 10.dp
    val radiusXl = 14.dp
    val radius2xl = 16.dp
    val radius4xl = 24.dp
    val radiusFull = 9999.dp
    val radiusLg = 12.dp
    val radius3xl = 20.dp
    val radius5xl = 28.dp
    val radius6xl = 32.dp
}
