// Auto-generated by build.js — do not edit.
package com.imin.designsystem.tokens

import androidx.compose.ui.text.TextStyle
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.unit.sp

object Typography {
    val headingMdRegular = TextStyle(
        fontSize = 36.sp,
        fontWeight = FontWeight.Normal,
        lineHeight = 44.sp,
    )

    val headingMdMedium = TextStyle(
        fontSize = 36.sp,
        fontWeight = FontWeight.Medium,
        lineHeight = 44.sp,
    )

    val headingMdSemibold = TextStyle(
        fontSize = 36.sp,
        fontWeight = FontWeight.SemiBold,
        lineHeight = 44.sp,
    )

    val headingMdBold = TextStyle(
        fontSize = 36.sp,
        fontWeight = FontWeight.Bold,
        lineHeight = 44.sp,
    )

    val headingSmRegular = TextStyle(
        fontSize = 32.sp,
        fontWeight = FontWeight.Normal,
        lineHeight = 40.sp,
    )

    val headingSmMedium = TextStyle(
        fontSize = 32.sp,
        fontWeight = FontWeight.Medium,
        lineHeight = 40.sp,
    )

    val headingSmSemibold = TextStyle(
        fontSize = 32.sp,
        fontWeight = FontWeight.SemiBold,
        lineHeight = 40.sp,
    )

    val headingSmBold = TextStyle(
        fontSize = 32.sp,
        fontWeight = FontWeight.Bold,
        lineHeight = 40.sp,
    )

    val headingXsRegular = TextStyle(
        fontSize = 24.sp,
        fontWeight = FontWeight.Normal,
        lineHeight = 32.sp,
    )

    val headingXsMedium = TextStyle(
        fontSize = 24.sp,
        fontWeight = FontWeight.Medium,
        lineHeight = 32.sp,
    )

    val headingXsSemibold = TextStyle(
        fontSize = 24.sp,
        fontWeight = FontWeight.SemiBold,
        lineHeight = 32.sp,
    )

    val headingXsBold = TextStyle(
        fontSize = 24.sp,
        fontWeight = FontWeight.Bold,
        lineHeight = 32.sp,
    )

    val bodyLgRegular = TextStyle(
        fontSize = 24.sp,
        fontWeight = FontWeight.Normal,
        lineHeight = 26.sp,
    )

    val bodyLgMedium = TextStyle(
        fontSize = 24.sp,
        fontWeight = FontWeight.Medium,
        lineHeight = 26.sp,
    )

    val bodyLgSemibold = TextStyle(
        fontSize = 24.sp,
        fontWeight = FontWeight.SemiBold,
        lineHeight = 26.sp,
    )

    val bodyLgBold = TextStyle(
        fontSize = 24.sp,
        fontWeight = FontWeight.Bold,
        lineHeight = 26.sp,
    )

    val bodyMdRegular = TextStyle(
        fontSize = 16.sp,
        fontWeight = FontWeight.Normal,
        lineHeight = 24.sp,
    )

    val bodyMdMedium = TextStyle(
        fontSize = 16.sp,
        fontWeight = FontWeight.Medium,
        lineHeight = 24.sp,
    )

    val bodyMdSemibold = TextStyle(
        fontSize = 16.sp,
        fontWeight = FontWeight.SemiBold,
        lineHeight = 24.sp,
    )

    val bodyMdBold = TextStyle(
        fontSize = 16.sp,
        fontWeight = FontWeight.Bold,
        lineHeight = 24.sp,
    )

    val bodySmRegular = TextStyle(
        fontSize = 14.sp,
        fontWeight = FontWeight.Normal,
        lineHeight = 20.sp,
    )

    val bodySmMedium = TextStyle(
        fontSize = 14.sp,
        fontWeight = FontWeight.Medium,
        lineHeight = 20.sp,
    )

    val bodySmSemibold = TextStyle(
        fontSize = 14.sp,
        fontWeight = FontWeight.SemiBold,
        lineHeight = 20.sp,
    )

    val bodySmBold = TextStyle(
        fontSize = 14.sp,
        fontWeight = FontWeight.Bold,
        lineHeight = 20.sp,
    )

    val bodyXsRegular = TextStyle(
        fontSize = 12.sp,
        fontWeight = FontWeight.Normal,
        lineHeight = 18.sp,
    )

    val bodyXsMedium = TextStyle(
        fontSize = 12.sp,
        fontWeight = FontWeight.Medium,
        lineHeight = 18.sp,
    )

    val bodyXsSemibold = TextStyle(
        fontSize = 12.sp,
        fontWeight = FontWeight.SemiBold,
        lineHeight = 18.sp,
    )

    val bodyXsBold = TextStyle(
        fontSize = 12.sp,
        fontWeight = FontWeight.Bold,
        lineHeight = 18.sp,
    )

    val bodyXsSemoBold = TextStyle(
        fontSize = 12.sp,
        fontWeight = FontWeight.SemiBold,
        lineHeight = 18.sp,
    )

    val headingXlRegular = TextStyle(
        fontSize = 48.sp,
        fontWeight = FontWeight.Normal,
        lineHeight = 56.sp,
    )

    val headingXlMedium = TextStyle(
        fontSize = 48.sp,
        fontWeight = FontWeight.Medium,
        lineHeight = 56.sp,
    )

    val headingXlSemibold = TextStyle(
        fontSize = 48.sp,
        fontWeight = FontWeight.SemiBold,
        lineHeight = 56.sp,
    )

    val headingXlBold = TextStyle(
        fontSize = 48.sp,
        fontWeight = FontWeight.Bold,
        lineHeight = 56.sp,
    )

    val headingXlSemiBold = TextStyle(
        fontSize = 48.sp,
        fontWeight = FontWeight.SemiBold,
        lineHeight = 56.sp,
    )

    val headingLgRegular = TextStyle(
        fontSize = 40.sp,
        fontWeight = FontWeight.Normal,
        lineHeight = 48.sp,
    )

    val headingLgMedium = TextStyle(
        fontSize = 40.sp,
        fontWeight = FontWeight.Medium,
        lineHeight = 48.sp,
    )

    val headingLgSemibold = TextStyle(
        fontSize = 40.sp,
        fontWeight = FontWeight.SemiBold,
        lineHeight = 48.sp,
    )

    val headingLgBold = TextStyle(
        fontSize = 40.sp,
        fontWeight = FontWeight.Bold,
        lineHeight = 48.sp,
    )

    val headingLgSemiBold = TextStyle(
        fontSize = 40.sp,
        fontWeight = FontWeight.SemiBold,
        lineHeight = 48.sp,
    )

    val bodyXlRegular = TextStyle(
        fontSize = 20.sp,
        fontWeight = FontWeight.Normal,
        lineHeight = 28.sp,
    )

    val bodyXlMedium = TextStyle(
        fontSize = 20.sp,
        fontWeight = FontWeight.Medium,
        lineHeight = 28.sp,
    )

    val bodyXlSemibold = TextStyle(
        fontSize = 20.sp,
        fontWeight = FontWeight.SemiBold,
        lineHeight = 28.sp,
    )

    val bodyXlBold = TextStyle(
        fontSize = 20.sp,
        fontWeight = FontWeight.Bold,
        lineHeight = 28.sp,
    )

    val bodyXlSemiBold = TextStyle(
        fontSize = 20.sp,
        fontWeight = FontWeight.SemiBold,
        lineHeight = 28.sp,
    )

    val carmenSansHeadingLgRegular = TextStyle(
        fontSize = 40.sp,
        fontWeight = FontWeight.Normal,
        lineHeight = 48.sp,
    )

    val carmenSansHeadingLgBold = TextStyle(
        fontSize = 40.sp,
        fontWeight = FontWeight.Bold,
        lineHeight = 48.sp,
    )

    val carmenSansHeadingLgExtraBold = TextStyle(
        fontSize = 40.sp,
        fontWeight = FontWeight.ExtraBold,
        lineHeight = 48.sp,
    )

    val carmenSansHeadingXsRegular = TextStyle(
        fontSize = 24.sp,
        fontWeight = FontWeight.Normal,
        lineHeight = 32.sp,
    )

    val carmenSansHeadingXsBold = TextStyle(
        fontSize = 24.sp,
        fontWeight = FontWeight.Bold,
        lineHeight = 32.sp,
    )

    val carmenSansHeadingXsExtraBold = TextStyle(
        fontSize = 24.sp,
        fontWeight = FontWeight.ExtraBold,
        lineHeight = 32.sp,
    )

    val carmenSansHeadingSmRegular = TextStyle(
        fontSize = 32.sp,
        fontWeight = FontWeight.Normal,
        lineHeight = 40.sp,
    )

    val carmenSansHeadingSmBold = TextStyle(
        fontSize = 32.sp,
        fontWeight = FontWeight.Bold,
        lineHeight = 40.sp,
    )

    val carmenSansHeadingSmExtraBold = TextStyle(
        fontSize = 32.sp,
        fontWeight = FontWeight.ExtraBold,
        lineHeight = 40.sp,
    )

    val carmenSansBodyXlRegualr = TextStyle(
        fontSize = 16.sp,
        fontWeight = FontWeight.Normal,
        lineHeight = 24.sp,
    )

    val carmenSansBodyXlBold = TextStyle(
        fontSize = 16.sp,
        fontWeight = FontWeight.Bold,
        lineHeight = 24.sp,
    )

    val carmenSansBodyXlExtraBold = TextStyle(
        fontSize = 16.sp,
        fontWeight = FontWeight.ExtraBold,
        lineHeight = 24.sp,
    )

    val carmenSansHeadingXlRegular = TextStyle(
        fontSize = 48.sp,
        fontWeight = FontWeight.Normal,
        lineHeight = 56.sp,
    )

    val carmenSansHeadingXlBold = TextStyle(
        fontSize = 48.sp,
        fontWeight = FontWeight.Bold,
        lineHeight = 56.sp,
    )

    val carmenSansHeadingXlExtraBold = TextStyle(
        fontSize = 48.sp,
        fontWeight = FontWeight.ExtraBold,
        lineHeight = 56.sp,
    )

    val carmenSansBodyMdRegular = TextStyle(
        fontSize = 16.sp,
        fontWeight = FontWeight.Normal,
        lineHeight = 24.sp,
    )

    val carmenSansBodyMdBold = TextStyle(
        fontSize = 16.sp,
        fontWeight = FontWeight.Bold,
        lineHeight = 24.sp,
    )

    val carmenSansBodyMdExtraBold = TextStyle(
        fontSize = 16.sp,
        fontWeight = FontWeight.ExtraBold,
        lineHeight = 24.sp,
    )

    val carmenSansBodySmRegular = TextStyle(
        fontSize = 14.sp,
        fontWeight = FontWeight.Normal,
        lineHeight = 20.sp,
    )

    val carmenSansBodySmBold = TextStyle(
        fontSize = 14.sp,
        fontWeight = FontWeight.Bold,
        lineHeight = 20.sp,
    )

    val carmenSansBodySmExtraBold = TextStyle(
        fontSize = 14.sp,
        fontWeight = FontWeight.ExtraBold,
        lineHeight = 20.sp,
    )

    val carmenSansBodyXsRegular = TextStyle(
        fontSize = 12.sp,
        fontWeight = FontWeight.Normal,
        lineHeight = 18.sp,
    )

    val carmenSansBodyXsBold = TextStyle(
        fontSize = 12.sp,
        fontWeight = FontWeight.Bold,
        lineHeight = 18.sp,
    )

    val carmenSansBodyXsExtraBold = TextStyle(
        fontSize = 12.sp,
        fontWeight = FontWeight.ExtraBold,
        lineHeight = 18.sp,
    )
}
