// Auto-generated by build.js — do not edit.
import CoreGraphics

public enum DSSpacing {
    public static let none: CGFloat = 0
    public static let xxs: CGFloat = 2
    public static let xs: CGFloat = 4
    public static let md: CGFloat = 8
    public static let lg: CGFloat = 12
    public static let xl: CGFloat = 16
    public static let xl2: CGFloat = 20
    public static let xl3: CGFloat = 24
    public static let xl4: CGFloat = 32
    public static let xl6: CGFloat = 48
    public static let xl7: CGFloat = 64
    public static let xl8: CGFloat = 80
    public static let xl9: CGFloat = 96
    public static let xl10: CGFloat = 128
    public static let xl11: CGFloat = 160
    public static let sm: CGFloat = 6
    public static let xl5: CGFloat = 40
}
