// Auto-generated by build.js — do not edit.
import CoreGraphics

public enum Spacing {
    public static let spacing00px: CGFloat = 0
    public static let spacing052px: CGFloat = 2
    public static let spacing14px: CGFloat = 4
    public static let spacing28px: CGFloat = 8
    public static let spacing312px: CGFloat = 12
    public static let spacing416px: CGFloat = 16
    public static let spacing520px: CGFloat = 20
    public static let spacing624px: CGFloat = 24
    public static let spacing832px: CGFloat = 32
    public static let spacing1040px: CGFloat = 40
    public static let spacing1248px: CGFloat = 48
    public static let spacing1664px: CGFloat = 64
    public static let spacing2080px: CGFloat = 80
    public static let spacing2496px: CGFloat = 96
    public static let spacing32128px: CGFloat = 128
    public static let spacing40160px: CGFloat = 160
    public static let spacing48192px: CGFloat = 192
    public static let spacing56224px: CGFloat = 224
    public static let spacing64256px: CGFloat = 256
    public static let spacing96384px: CGFloat = 384
    public static let spacing80320px: CGFloat = 320
    public static let spacing120480px: CGFloat = 480
    public static let spacing160640px: CGFloat = 640
    public static let spacing192768px: CGFloat = 768
    public static let spacing2561024px: CGFloat = 1024
    public static let spacing3201280px: CGFloat = 1280
    public static let spacing3601440px: CGFloat = 1440
    public static let spacing4001600px: CGFloat = 1600
    public static let spacing4801920px: CGFloat = 1920
    public static let spacing156px: CGFloat = 6
    public static let spacing140560px: CGFloat = 560
    public static let spacing180720px: CGFloat = 720
    public static let spacingNone: CGFloat = 0
    public static let spacingXxs: CGFloat = 2
    public static let spacingXs: CGFloat = 4
    public static let spacingMd: CGFloat = 8
    public static let spacingLg: CGFloat = 12
    public static let spacingXl: CGFloat = 16
    public static let spacing2xl: CGFloat = 20
    public static let spacing3xl: CGFloat = 24
    public static let spacing4xl: CGFloat = 32
    public static let spacing6xl: CGFloat = 48
    public static let spacing7xl: CGFloat = 64
    public static let spacing8xl: CGFloat = 80
    public static let spacing9xl: CGFloat = 96
    public static let spacing10xl: CGFloat = 128
    public static let spacing11xl: CGFloat = 160
    public static let spacingSm: CGFloat = 6
    public static let spacing5xl: CGFloat = 40
}

public enum Radius {
    public static let radiusNone: CGFloat = 0
    public static let radiusXxs: CGFloat = 4
    public static let radiusXs: CGFloat = 6
    public static let radiusSm: CGFloat = 8
    public static let radiusMd: CGFloat = 10
    public static let radiusXl: CGFloat = 14
    public static let radius2xl: CGFloat = 16
    public static let radius4xl: CGFloat = 24
    public static let radiusFull: CGFloat = 9999
    public static let radiusLg: CGFloat = 12
    public static let radius3xl: CGFloat = 20
    public static let radius5xl: CGFloat = 28
    public static let radius6xl: CGFloat = 32
}
