import { stripPx, isNumericLike } from './utils.js';

const PACKAGE = 'com.imin.designsystem.tokens';

export function androidSpacingFormat({ dictionary }) {
  const spacing = dictionary.allTokens.filter((t) => {
    const p0 = (t.path?.[0] || '').toLowerCase();
    const typed = t.$type === 'dimension' || t.$type === 'spacing' || t.$type === 'number';
    return typed && /^spacing/.test(p0) && isNumericLike(t.$value);
  });
  const radius = dictionary.allTokens.filter((t) => {
    const p0 = (t.path?.[0] || '').toLowerCase();
    const typed = t.$type === 'borderRadius' || t.$type === 'number';
    return typed && /^radius/.test(p0) && isNumericLike(t.$value);
  });

  const lineFor = (t) => `    val ${t.name} = ${stripPx(t.$value)}.dp`;

  return `// Auto-generated by build.js — do not edit.
package ${PACKAGE}

import androidx.compose.ui.unit.dp

object Spacing {
${spacing.map(lineFor).join('\n')}
}

object Radius {
${radius.map(lineFor).join('\n')}
}
`;
}

export const androidSpacingFormatDef = {
  name: 'android/compose-spacing',
  format: androidSpacingFormat,
};
