/**
 * Style Dictionary format: Jetpack Compose Color object.
 *
 * Options:
 *   objectName — e.g., 'LightColors' or 'DarkColors'
 */

const PACKAGE = 'com.imin.designsystem.tokens';

/**
 * Returns true if a color value string is a plain color (hex or rgb/rgba),
 * not a gradient or other complex CSS value.
 */
function isPlainColor(value) {
  return typeof value === 'string' && (
    value.startsWith('#') || /^rgba?\s*\(/i.test(value)
  );
}

/**
 * Parse hex (#RGB, #RRGGBB, #RRGGBBAA) or rgba()/rgb() to {r, g, b, a} 0-255 ints.
 */
function parseColor(value) {
  if (value.startsWith('#')) {
    let h = value.slice(1);
    if (h.length === 3) h = h.split('').map((c) => c + c).join('') + 'ff';
    else if (h.length === 6) h += 'ff';
    return {
      r: parseInt(h.slice(0, 2), 16),
      g: parseInt(h.slice(2, 4), 16),
      b: parseInt(h.slice(4, 6), 16),
      a: parseInt(h.slice(6, 8), 16),
    };
  }
  const m = value.match(/^rgba?\s*\(\s*(\d+)\s*,\s*(\d+)\s*,\s*(\d+)\s*(?:,\s*(\d*\.?\d+)\s*)?\)$/i);
  if (!m) return null;
  return {
    r: Number(m[1]),
    g: Number(m[2]),
    b: Number(m[3]),
    a: m[4] !== undefined ? Math.round(Number(m[4]) * 255) : 255,
  };
}

function toComposeArgb({ r, g, b, a }) {
  const hex = (n) => n.toString(16).padStart(2, '0').toUpperCase();
  return `0x${hex(a)}${hex(r)}${hex(g)}${hex(b)}`;
}

export function androidColorsFormat({ dictionary, options }) {
  const objectName = options?.objectName || 'Colors';
  const lines = dictionary.allTokens
    .filter((t) => t.$type === 'color' && isPlainColor(t.$value))
    .map((t) => {
      const rgba = parseColor(t.$value);
      if (!rgba) return null;
      return `    val ${t.name} = Color(${toComposeArgb(rgba)})`;
    })
    .filter(Boolean);

  return `// Auto-generated by build.js — do not edit.
package ${PACKAGE}

import androidx.compose.ui.graphics.Color

object ${objectName} {
${lines.join('\n')}
}
`;
}

export const androidColorsFormatDef = {
  name: 'android/compose-colors',
  format: androidColorsFormat,
};
