import { stripPx } from './utils.js';

function weightToken(weight) {
  const n = Number(weight);
  if (n <= 200) return 'ultraLight';
  if (n <= 300) return 'light';
  if (n <= 400) return 'regular';
  if (n <= 500) return 'medium';
  if (n <= 600) return 'semibold';
  if (n <= 700) return 'bold';
  if (n <= 800) return 'heavy';
  return 'black';
}

function parseTypoValue(raw) {
  if (raw && typeof raw === 'object') return raw;
  if (typeof raw !== 'string') return {};
  const m = raw.match(/^\s*(\d+)\s+(-?\d+(?:\.\d+)?(?:px)?)(?:\/(-?\d+(?:\.\d+)?(?:px)?))?\s+(.+?)\s*$/);
  if (!m) return {};
  return {
    fontWeight: Number(m[1]),
    fontSize: m[2],
    lineHeight: m[3],
    fontFamily: m[4],
  };
}

export function generateDSFont(allTokens) {
  const typo = allTokens.filter((t) => t.$type === 'typography');
  const lines = typo.map((t) => {
    const v = parseTypoValue(t.$value);
    const size = stripPx(v.fontSize ?? '16');
    const weight = weightToken(v.fontWeight ?? 400);
    const fontExpr = v.fontFamily
      ? `Font.custom("${v.fontFamily}", size: ${size})`
      : `Font.system(size: ${size})`;
    return `    public static let ${t.name}: Font = { _ = _registered; return ${fontExpr}.weight(.${weight}) }()`;
  });

  return `// Auto-generated by build.js — do not edit.
import SwiftUI

public enum DSFont {
    // Pretendard 폰트 자동 등록 — 어떤 멤버에 처음 접근해도 1회 실행됨
    private static let _registered: Void = DSFontRegistration.register()

${lines.join('\n')}
}
`;
}
