import { stripPx, isNumericLike } from './utils.js';

export function iosSpacingFormat({ dictionary }) {
  const spacing = dictionary.allTokens.filter((t) => {
    const p0 = (t.path?.[0] || '').toLowerCase();
    const typed = t.$type === 'dimension' || t.$type === 'spacing' || t.$type === 'number';
    return typed && /^spacing/.test(p0) && isNumericLike(t.$value);
  });
  const radius = dictionary.allTokens.filter((t) => {
    const p0 = (t.path?.[0] || '').toLowerCase();
    const typed = t.$type === 'borderRadius' || t.$type === 'number';
    return typed && /^radius/.test(p0) && isNumericLike(t.$value);
  });

  const lineFor = (t) => `    public static let ${t.name}: CGFloat = ${stripPx(t.$value)}`;

  return `// Auto-generated by build.js — do not edit.
import CoreGraphics

public enum Spacing {
${spacing.map(lineFor).join('\n')}
}

public enum Radius {
${radius.map(lineFor).join('\n')}
}
`;
}

export const iosSpacingFormatDef = {
  name: 'ios/spacing-radius',
  format: iosSpacingFormat,
};
