/**
 * Style Dictionary format: SwiftUI Color namespace enum.
 *
 * Options:
 *   namespace — e.g., 'LightColors' or 'DarkColors'
 */

/**
 * Returns true if a color value string is a plain color (hex or rgb/rgba),
 * not a gradient or other complex CSS value.
 */
function isPlainColor(value) {
  if (typeof value !== 'string') return false;
  const v = value.trim();
  return v.startsWith('#') || /^rgba?\s*\(/i.test(v);
}

/**
 * Parse a color value into { r, g, b, a } with components in [0, 1].
 * Handles:
 *   - #RGB
 *   - #RRGGBB
 *   - #RRGGBBAA
 *   - rgb(r, g, b)          where r/g/b are 0-255
 *   - rgba(r, g, b, a)      where r/g/b are 0-255 and a is 0-1
 */
function parseColor(value) {
  if (typeof value === 'string' && value.startsWith('#')) {
    return parseHex(value);
  }

  if (typeof value === 'string') {
    // rgba(r, g, b, a) or rgb(r, g, b)
    const rgbaMatch = value.match(/rgba?\(\s*([\d.]+)\s*,\s*([\d.]+)\s*,\s*([\d.]+)(?:\s*,\s*([\d.]+))?\s*\)/i);
    if (rgbaMatch) {
      const r = parseFloat(rgbaMatch[1]) / 255;
      const g = parseFloat(rgbaMatch[2]) / 255;
      const b = parseFloat(rgbaMatch[3]) / 255;
      const a = rgbaMatch[4] !== undefined ? parseFloat(rgbaMatch[4]) : 1;
      return { r, g, b, a };
    }
  }

  // Fallback: try hex anyway
  return parseHex(String(value));
}

function parseHex(hex) {
  const h = hex.replace('#', '');
  const full = h.length === 3
    ? h.split('').map((c) => c + c).join('') + 'ff'
    : h.length === 6 ? h + 'ff' : h;
  const r = parseInt(full.slice(0, 2), 16) / 255;
  const g = parseInt(full.slice(2, 4), 16) / 255;
  const b = parseInt(full.slice(4, 6), 16) / 255;
  const a = parseInt(full.slice(6, 8), 16) / 255;
  return { r, g, b, a };
}

function fmt(n) {
  return Number(n.toFixed(4)).toString();
}

export function iosColorsFormat({ dictionary, options }) {
  const namespace = options?.namespace || 'Colors';
  const lines = dictionary.allTokens
    .filter((t) => t.$type === 'color' && isPlainColor(t.$value))
    .map((t) => {
      const { r, g, b, a } = parseColor(t.$value);
      return a < 1
        ? `    public static let ${t.name} = Color(red: ${fmt(r)}, green: ${fmt(g)}, blue: ${fmt(b)}, opacity: ${fmt(a)})`
        : `    public static let ${t.name} = Color(red: ${fmt(r)}, green: ${fmt(g)}, blue: ${fmt(b)})`;
    });

  return `// Auto-generated by build.js — do not edit.
import SwiftUI

public enum ${namespace} {
${lines.join('\n')}
}
`;
}

export const iosColorsFormatDef = {
  name: 'ios/colors-namespace',
  format: iosColorsFormat,
};
