import { stripPx } from './utils.js';

/**
 * Pure function: generate web/tokens.ts content from light + dark transformed token arrays.
 *
 * Inputs are SD-transformed tokens (post-name-camelCase, post-reference-resolve).
 * Each token has: name (string), $type (string), $value (string|object), path (string[]).
 * SD v5 always emits DTCG fields ($type/$value).
 */
export function generateTokensTs(lightTokens, darkTokens) {
  const lightColors = lightTokens.filter((t) => t.$type === 'color');
  const darkColors = darkTokens.filter((t) => t.$type === 'color');
  const spacing = lightTokens.filter(
    (t) => (t.$type === 'number' || t.$type === 'dimension' || t.$type === 'spacing')
      && /^spacing/i.test(t.path[0] || ''),
  );
  const radius = lightTokens.filter(
    (t) => (t.$type === 'number' || t.$type === 'borderRadius')
      && /^radius/i.test(t.path[0] || ''),
  );
  const typography = lightTokens.filter((t) => t.$type === 'typography');

  // Quote key if it contains characters invalid for unquoted TS identifiers (e.g. hyphens, digits-only start)
  const safeKey = (name) => /^[a-zA-Z_$][a-zA-Z0-9_$]*$/.test(name) ? name : `'${name}'`;

  const colorEntries = (tokens) =>
    tokens.map((t) => `    ${safeKey(t.name)}: '${t.$value}',`).join('\n');

  const dimEntries = (tokens) =>
    tokens.map((t) => {
      const v = stripPx(t.$value);
      return `  ${safeKey(t.name)}: ${typeof v === 'number' ? v : `'${v}'`},`;
    }).join('\n');

  /**
   * Parse a CSS font shorthand or composite object into individual properties.
   * SD v5 resolves typography composites into a CSS shorthand string, e.g.:
   *   '400 72px/90 Pretendard'  → { fontWeight: 400, fontSize: 72, lineHeight: 90, fontFamily: 'Pretendard' }
   * Test inputs pass a plain object with $value = { fontFamily, fontWeight, fontSize, lineHeight, ... }.
   */
  const parseTypoValue = (t) => {
    const raw = t.$value;

    // If value is already a plain object (test fixture format), use it directly
    if (raw && typeof raw === 'object') return raw;

    // If it's a string (SD v5 CSS shorthand), parse it
    // Format: "<fontWeight> <fontSize>[/<lineHeight>] <fontFamily...>"
    if (typeof raw === 'string') {
      const m = raw.match(/^(\S+)\s+(\d+(?:\.\d+)?(?:px|rem|em|%)?)\s*(?:\/\s*(\S+))?\s+(.+)$/);
      if (m) {
        const [, fw, fs, lh, ff] = m;
        return {
          fontFamily: ff.trim(),
          fontWeight: /^\d+$/.test(fw) ? Number(fw) : fw,
          fontSize: fs,
          lineHeight: lh,
        };
      }
    }

    return {};
  };

  const typoEntries = (tokens) =>
    tokens.map((t) => {
      const v = parseTypoValue(t);
      const parts = [];
      if (v.fontFamily) parts.push(`fontFamily: '${v.fontFamily}'`);
      if (v.fontWeight !== undefined) parts.push(`fontWeight: ${typeof v.fontWeight === 'number' ? v.fontWeight : `'${v.fontWeight}'`}`);
      if (v.fontSize) parts.push(`fontSize: ${stripPx(v.fontSize)}`);
      if (v.lineHeight !== undefined) parts.push(`lineHeight: ${stripPx(v.lineHeight)}`);
      if (v.letterSpacing) parts.push(`letterSpacing: ${stripPx(v.letterSpacing)}`);
      return `  ${safeKey(t.name)}: { ${parts.join(', ')} },`;
    }).join('\n');

  return `// Auto-generated by build.js — do not edit.
export const colors = {
  light: {
${colorEntries(lightColors)}
  },
  dark: {
${colorEntries(darkColors)}
  },
} as const;

export const spacing = {
${dimEntries(spacing)}
} as const;

export const radius = {
${dimEntries(radius)}
} as const;

export const typography = {
${typoEntries(typography)}
} as const;

export type ColorToken = keyof typeof colors.light;
export type SpacingToken = keyof typeof spacing;
export type RadiusToken = keyof typeof radius;
export type TypographyToken = keyof typeof typography;
`;
}
