/**
 * Pure function: generate web/tokens.ts content from light + dark transformed token arrays.
 *
 * Inputs are SD-transformed tokens (post-name-camelCase, post-reference-resolve).
 * Each token has: name (string), $type (string), $value (string|object), path (string[]).
 * Supports both DTCG ($type/$value) and SD v5 resolved (type/value) field names.
 */
export function generateTokensTs(lightTokens, darkTokens) {
  // Helper: read type from either DTCG ($type) or SD resolved (type)
  const getType = (t) => t.$type || t.type || '';
  // Helper: read value from either DTCG ($value) or SD resolved (value)
  const getValue = (t) => (t.$value !== undefined ? t.$value : t.value);

  const lightColors = lightTokens.filter((t) => getType(t) === 'color');
  const darkColors = darkTokens.filter((t) => getType(t) === 'color');
  const spacing = lightTokens.filter((t) => getType(t) === 'dimension' || getType(t) === 'spacing');
  const radius = lightTokens.filter((t) => getType(t) === 'borderRadius');
  const typography = lightTokens.filter((t) => getType(t) === 'typography');

  const stripPx = (v) => {
    if (typeof v !== 'string') return v;
    const m = v.match(/^(-?\d+(?:\.\d+)?)px$/);
    return m ? Number(m[1]) : v;
  };

  // Quote key if it contains characters invalid for unquoted TS identifiers (e.g. hyphens, digits-only start)
  const safeKey = (name) => /^[a-zA-Z_$][a-zA-Z0-9_$]*$/.test(name) ? name : `'${name}'`;

  const colorEntries = (tokens) =>
    tokens.map((t) => `    ${safeKey(t.name)}: '${getValue(t)}',`).join('\n');

  const dimEntries = (tokens) =>
    tokens.map((t) => `  ${safeKey(t.name)}: ${stripPx(getValue(t))},`).join('\n');

  /**
   * Parse a CSS font shorthand or composite object into individual properties.
   * SD v5 resolves typography composites into a CSS shorthand string, e.g.:
   *   '400 72px/90 Pretendard'  → { fontWeight: 400, fontSize: 72, lineHeight: 90, fontFamily: 'Pretendard' }
   * Test inputs pass a plain object with $value = { fontFamily, fontWeight, fontSize, lineHeight, ... }.
   */
  const parseTypoValue = (t) => {
    const raw = getValue(t);

    // If value is already a plain object (test fixture format), use it directly
    if (raw && typeof raw === 'object') return raw;

    // If it's a string (SD v5 CSS shorthand), parse it
    // Format: "<fontWeight> <fontSize>[/<lineHeight>] <fontFamily...>"
    if (typeof raw === 'string') {
      const m = raw.match(/^(\S+)\s+(\d+(?:\.\d+)?(?:px|rem|em|%)?)\s*(?:\/\s*(\S+))?\s+(.+)$/);
      if (m) {
        const [, fw, fs, lh, ff] = m;
        return {
          fontFamily: ff.trim(),
          fontWeight: /^\d+$/.test(fw) ? Number(fw) : fw,
          fontSize: fs,
          lineHeight: lh,
        };
      }
    }

    return {};
  };

  const typoEntries = (tokens) =>
    tokens.map((t) => {
      const v = parseTypoValue(t);
      const parts = [];
      if (v.fontFamily) parts.push(`fontFamily: '${v.fontFamily}'`);
      if (v.fontWeight !== undefined) parts.push(`fontWeight: ${typeof v.fontWeight === 'number' ? v.fontWeight : `'${v.fontWeight}'`}`);
      if (v.fontSize) parts.push(`fontSize: ${stripPx(v.fontSize)}`);
      if (v.lineHeight !== undefined) parts.push(`lineHeight: ${stripPx(v.lineHeight)}`);
      if (v.letterSpacing) parts.push(`letterSpacing: ${stripPx(v.letterSpacing)}`);
      return `  ${safeKey(t.name)}: { ${parts.join(', ')} },`;
    }).join('\n');

  return `// Auto-generated by build.js — do not edit.
export const colors = {
  light: {
${colorEntries(lightColors)}
  },
  dark: {
${colorEntries(darkColors)}
  },
} as const;

export const spacing = {
${dimEntries(spacing)}
} as const;

export const radius = {
${dimEntries(radius)}
} as const;

export const typography = {
${typoEntries(typography)}
} as const;

export type ColorToken = keyof typeof colors.light;
export type SpacingToken = keyof typeof spacing;
export type RadiusToken = keyof typeof radius;
export type TypographyToken = keyof typeof typography;
`;
}
